Develop
krossovok83/library_for_rubygarage pull request #5
Opened 2021-11-22 17:11 UTC by krossovok83

2021-11-22 17:29 UTC, papandreusa requested changes

2021-11-22 17:29 UTC, papandreusa commented on lib/class/library.rb
> +    @books = (1..50).map { Book.generate }
Pls make contants

2021-11-22 17:29 UTC, papandreusa commented on lib/module/stat.rb
> +# Calculate statistics for library
Remove comments, pls

2021-11-22 17:29 UTC, papandreusa commented on lib/module/stat.rb
> +      count += ordered_best_books.map { |order| order.order_reader.reader_name }.uniq.length
Use reduce method, pls

2021-11-23 10:46 UTC, krossovok83 commented on lib/class/library.rb
> +    @books = (1..50).map { Book.generate }
fix

2021-11-23 10:46 UTC, krossovok83 commented on lib/module/stat.rb
> +# Calculate statistics for library
fix

2021-11-23 10:46 UTC, krossovok83 commented on lib/module/stat.rb
> +      count += ordered_best_books.map { |order| order.order_reader.reader_name }.uniq.length
done

2021-11-23 10:48 UTC, closed without merging